# Generated by Django 3.1.1 on 2020-09-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200908_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='background_image_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
